import React from 'react'
import './About.css'

// Placeholder for images generated by tool
import profileImg from '../assets/about/profile.png'
import bridgeImg from '../assets/about/bridge.png'
import catImg from '../assets/about/cat.png'

// Company Logos
import ezwageLogo from '../assets/about/company/ezwage.png'
import fakirLogo from '../assets/about/company/fakir_apparels.png'
import insparofaithLogo from '../assets/about/company/insparofaith_games.png'
import mitroLogo from '../assets/about/company/mitro.png'
import undpLogo from '../assets/about/company/undp.png'
import duLogo from '../assets/about/company/university_of_dhaka.svg'
import ygenLogo from '../assets/about/company/ygen_engineering.png'
import yoyosoLogo from '../assets/about/company/yoyoso.png'

const About = () => {
    return (
        <div className="about-page fade-in">
            <section className="about-header">
                <div className="profile-tile">
                    <img src={profileImg} alt="Amit Rohan" />
                </div>
                <div className="header-info-container">
                    <div className="header-info">
                        <h1 className="header-name">Amit Rohan</h1>
                        <p className="header-subtitle">UI/UX Designer</p>
                    </div>
                    <div className="button-row">
                        <button className="btn-filled">Contact</button>
                        <button className="btn-outlined">Resume</button>
                    </div>
                </div>
            </section>

            <section className="about-bio">
                <p>
                    I am a UI/UX designer who integrates a formal background in fine arts with digital product design to solve complex visual and functional problems. With a Master's degree in Drawing and Painting, I apply principles of composition and color theory to create intuitive interfaces across the ed-tech, fintech, and mobile gaming sectors. By combining user research with iterative design, I translate intricate requirements into scalable systems that enhance user engagement and simplify the digital experience.
                </p>

            </section>

            <hr />

            <section className="experience-section">
                <h3 className="section-title">Experience</h3>
                <div className="experience-list">
                    <div className="experience-item">
                        <div className="exp-main">
                            <span className="exp-company">Insparofaith Games</span>
                            <span className="exp-role">UI/UX Designer & Digital Artist</span>
                        </div>
                        <span className="exp-date">2021 — Present</span>
                    </div>
                    <div className="experience-item">
                        <div className="exp-main">
                            <span className="exp-company">EZ Wage Ltd.</span>
                            <span className="exp-role">UI/UX Designer</span>
                        </div>
                        <span className="exp-date">2022 — 2023</span>
                    </div>
                    <div className="experience-item">
                        <div className="exp-main">
                            <span className="exp-company">Yoyoso Bangladesh</span>
                            <span className="exp-role">Creative Visualizer (Contract)</span>
                        </div>
                        <span className="exp-date">2023 — Present</span>
                    </div>
                    <div className="experience-item">
                        <div className="exp-main">
                            <span className="exp-company">UNDP</span>
                            <span className="exp-role">Graphic Designer</span>
                        </div>
                        <span className="exp-date">2019 — 2020</span>
                    </div>
                </div>
            </section>

            <hr />

            <section className="experience-section">
                <h3 className="section-title">Education</h3>
                <div className="experience-list">
                    <div className="experience-item">
                        <div className="exp-main">
                            <span className="exp-company">University of Dhaka</span>
                            <span className="exp-role">Master of Fine Arts (MFA)</span>
                        </div>
                    </div>
                    <div className="experience-item">
                        <div className="exp-main">
                            <span className="exp-company">University of Dhaka</span>
                            <span className="exp-role">Bachelor of Fine Arts (BFA)</span>
                        </div>
                    </div>
                </div>
            </section>

            <hr />

            <section className="experience-section">
                <h3 className="section-title">Certifications</h3>
                <div className="experience-list">
                    <div className="experience-item">
                        <div className="exp-main">
                            <span className="exp-company">Advanced UI/UX Design</span>
                            <span className="exp-role">Coursera / Google</span>
                        </div>
                    </div>
                    <div className="experience-item">
                        <div className="exp-main">
                            <span className="exp-company">Unreal Engine 5 for Professionals</span>
                            <span className="exp-role">Epic Games</span>
                        </div>
                    </div>
                </div>
            </section>

            <hr />

            <section className="experience-section">
                <h3 className="section-title">Interest</h3>
                <div className="interests-grid">
                    <span className="interest-tag">Character Design</span>
                    <span className="interest-tag">Conceptualization</span>
                    <span className="interest-tag">Art & Technology</span>
                    <span className="interest-tag">Game Design & Development</span>
                </div>
            </section>

            <hr />

            <section className="companies-section">
                <h3 className="section-title">Companies I've worked with</h3>
                <div className="companies-grid">
                    <div className="company-logo"><img src={ezwageLogo} alt="EZ Wage" /></div>
                    <div className="company-logo"><img src={yoyosoLogo} alt="Yoyoso" /></div>
                    <div className="company-logo"><img src={undpLogo} alt="UNDP" /></div>
                    <div className="company-logo"><img src={fakirLogo} alt="Fakir Apparels" /></div>
                    <div className="company-logo"><img src={duLogo} alt="University of Dhaka" /></div>
                    <div className="company-logo"><img src={insparofaithLogo} alt="Insparofaith Games" /></div>
                    <div className="company-logo"><img src={mitroLogo} alt="Mitro" /></div>
                    <div className="company-logo"><img src={ygenLogo} alt="Ygen Engineering" /></div>
                </div>
            </section>

            <hr />

            <section className="testimonials-section">
                <h3 className="section-title">People I've worked with</h3>
                <div className="testimonial-card">
                    <p className="testimonial-text">
                        "I've had the pleasure of working with Amit on many projects over many
                        years now. He brings a magical touch to every design he works on and all
                        our shared users benefit."
                    </p>
                    <div className="testimonial-author">
                        <div className="author-avatar">
                            {/* In a real app, this would be an image. Using a placeholder or initial */}
                            <img src="https://ui-avatars.com/api/?name=Liam+Gladdy&background=random" alt="Liam Gladdy" />
                        </div>
                        <div className="author-info">
                            <span className="author-name">Liam Gladdy</span>
                            <span className="author-role">Senior Developer at WP Engine</span>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    )
}

export default About
